// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH4Itg60AN9wCXOMTAkbWUa8RSoTSfq5M',
    appId: '1:470379668610:web:6ce70648cb33b48ca0009b',
    messagingSenderId: '470379668610',
    projectId: 'flutter-base-331c1',
    authDomain: 'flutter-base-331c1.firebaseapp.com',
    storageBucket: 'flutter-base-331c1.firebasestorage.app',
    measurementId: 'G-2XNZ2Q85YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv1R6fUrqhI92dW-87Xcc70cM1XVrQftY',
    appId: '1:470379668610:android:50c27285de51bbfba0009b',
    messagingSenderId: '470379668610',
    projectId: 'flutter-base-331c1',
    storageBucket: 'flutter-base-331c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOAGq9bEClx4rwKKDaWf8ayX1dLmyq9pQ',
    appId: '1:470379668610:ios:e8f9748251470392a0009b',
    messagingSenderId: '470379668610',
    projectId: 'flutter-base-331c1',
    storageBucket: 'flutter-base-331c1.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOAGq9bEClx4rwKKDaWf8ayX1dLmyq9pQ',
    appId: '1:470379668610:ios:e8f9748251470392a0009b',
    messagingSenderId: '470379668610',
    projectId: 'flutter-base-331c1',
    storageBucket: 'flutter-base-331c1.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH4Itg60AN9wCXOMTAkbWUa8RSoTSfq5M',
    appId: '1:470379668610:web:2533a04b8a0e4353a0009b',
    messagingSenderId: '470379668610',
    projectId: 'flutter-base-331c1',
    authDomain: 'flutter-base-331c1.firebaseapp.com',
    storageBucket: 'flutter-base-331c1.firebasestorage.app',
    measurementId: 'G-JC5395DQN1',
  );
}
